// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlsstheftxbasainpfvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsc3N0aGVmdHhiYXNhaW5wZnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDIyMjQsImV4cCI6MjA2NzQxODIyNH0.VKQHDKqrWVNWDnzmsehLr_3fQr9TCeAAP3CO-bGtETs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});