// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://tjaofevfgtmaajcoiqsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYW9mZXZmZ3RtYWFqY29pcXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDU5MDUsImV4cCI6MjA2OTM4MTkwNX0.Z-x9TGYFCSplqbNUNqAd4u_pyvcGd4nJvjM4d2mwgLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
